package com.example.studyfocus.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF65558F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE9DDFF)
val onPrimaryContainerLight = Color(0xFF201047)
val secondaryLight = Color(0xFF5B5B5C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DDFF)
val onSecondaryContainerLight = Color(0xFF201047)
val tertiaryLight = Color(0xFF8B4A61)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E3)
val onTertiaryContainerLight = Color(0xFF3A071E)
val errorLight = Color(0xFF904A45)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD7)
val onErrorContainerLight = Color(0xFF3B0908)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1B20)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1D1B20)
val surfaceVariantLight = Color(0xFFE7E0EB)
val onSurfaceVariantLight = Color(0xFF49454E)
val outlineLight = Color(0xFF7A757F)
val outlineVariantLight = Color(0xFFCAC4CF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F35)
val inverseOnSurfaceLight = Color(0xFFF5EFF7)
val inversePrimaryLight = Color(0xFFCFBDFE)


val primaryDark = Color(0xFFCFBDFE)
val onPrimaryDark = Color(0xFF36275D)
val primaryContainerDark = Color(0xFF4D3D75)
val onPrimaryContainerDark = Color(0xFFE9DDFF)
val secondaryDark = Color(0xFFCFBDFE)
val onSecondaryDark = Color(0xFF36275D)
val secondaryContainerDark = Color(0xFF4D3D75)
val onSecondaryContainerDark = Color(0xFFE9DDFF)
val tertiaryDark = Color(0xFFFFB0C9)
val onTertiaryDark = Color(0xFF541D33)
val tertiaryContainerDark = Color(0xFF6F3349)
val onTertiaryContainerDark = Color(0xFFFFD9E3)
val errorDark = Color(0xFFFFB3AD)
val onErrorDark = Color(0xFF571E1B)
val errorContainerDark = Color(0xFF73332F)
val onErrorContainerDark = Color(0xFFFFDAD7)
val backgroundDark = Color(0xFF141218)
val onBackgroundDark = Color(0xFFE6E0E9)
val surfaceDark = Color(0xFF141218)
val onSurfaceDark = Color(0xFFE6E0E9)
val surfaceVariantDark = Color(0xFF49454E)
val onSurfaceVariantDark = Color(0xFFCAC4CF)
val outlineDark = Color(0xFF948F99)
val outlineVariantDark = Color(0xFF49454E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E0E9)
val inverseOnSurfaceDark = Color(0xFF322F35)
val inversePrimaryDark = Color(0xFF65558F)
